name: build dep

on:
  #push:
   # branches:
    #  - "main"
  schedule:
    - cron: "0 8 1 * *"


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set env
        run: echo "NOW=$(date +'%d%m%Y')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: dep-builder/.
          push: true
          tags: bjornjorgensen/dep-builder:${{ env.NOW }} , bjornjorgensen/dep-builder:latest
