name: Update GitHub Actions

on:
  schedule:
    - cron: '0 8 * * MON'  # Weekly on Monday at 8 AM UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pull-requests: write

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update GitHub Actions versions
        uses: nickderobertis/action-update-action-versions@v1
        with:
          # Create a PR with the updates
          create-pull-request: true
          # PR configuration
          pr-title: 'Update GitHub Actions to latest versions'
          pr-body: |
            🤖 **Automated GitHub Actions Update**
            
            This PR updates GitHub Actions to their latest versions for security and feature improvements.
            
            ### Changes Made:
            - Updated action versions to latest releases
            - Maintained compatibility with existing workflows
            
            ### Review Checklist:
            - [ ] All workflow files syntax is valid
            - [ ] No breaking changes in updated actions
            - [ ] Test workflows run successfully
            
            **Note**: This PR was created automatically. Please review the changes before merging.
          pr-branch: 'update-github-actions'
          # Only update these specific actions (optional - remove to update all)
          actions-to-update: |
            actions/checkout
            docker/setup-qemu-action
            docker/setup-buildx-action
            docker/login-action
            docker/build-push-action

  check-action-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check for outdated actions
        id: check
        run: |
          echo "Checking for outdated GitHub Actions..."
          
          # Find all workflow files
          workflow_files=$(find .github/workflows -name "*.yml" -o -name "*.yaml")
          
          outdated_actions=""
          
          for file in $workflow_files; do
            echo "Checking $file..."
            
            # Extract action uses with versions
            grep -n "uses:" "$file" | while read -r line; do
              line_num=$(echo "$line" | cut -d: -f1)
              action_ref=$(echo "$line" | sed 's/.*uses: *//; s/ *$//')
              
              # Skip local actions or actions without version
              if [[ "$action_ref" == ./* ]] || [[ "$action_ref" != *"@"* ]]; then
                continue
              fi
              
              action_name=$(echo "$action_ref" | cut -d@ -f1)
              current_version=$(echo "$action_ref" | cut -d@ -f2)
              
              echo "Found: $action_name@$current_version in $file:$line_num"
            done
          done

      - name: Create issue for manual review
        if: github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🔄 Weekly GitHub Actions Version Check';
            const body = `
            ## Weekly GitHub Actions Version Check
            
            This is an automated check to remind you to review GitHub Actions versions.
            
            ### Current Actions in Use:
            
            **Main Build Workflow:**
            - \`actions/checkout@v5\`
            - \`docker/setup-qemu-action@v3\`
            - \`docker/setup-buildx-action@v3\`
            - \`docker/login-action@v3\`
            - \`docker/build-push-action@v6\`
            
            ### Recommended Actions:
            
            1. **Check for updates**: Visit each action's repository to see if newer versions are available
            2. **Review changelogs**: Check for breaking changes or security fixes
            3. **Test updates**: Update versions in a separate branch and test workflows
            4. **Update workflow files**: Apply updates after testing
            
            ### Useful Resources:
            
            - [GitHub Actions Marketplace](https://github.com/marketplace?type=actions)
            - [Action Version Updates Best Practices](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
            
            ---
            
            *This issue was created automatically and can be closed after review.*
            `;
            
            // Check if similar issue already exists
            const existingIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'automation,github-actions'
            });
            
            const hasExistingIssue = existingIssues.data.some(issue => 
              issue.title.includes('Weekly GitHub Actions Version Check')
            );
            
            if (!hasExistingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['automation', 'github-actions', 'maintenance']
              });
              
              console.log('Created issue for GitHub Actions version check');
            } else {
              console.log('Similar issue already exists, skipping creation');
            }