name: Weekly Action Update Reminder

on:
  schedule:
    - cron: '0 10 * * MON'  # Weekly on Monday at 10 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  create-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create update reminder issue
        uses: actions/github-script@v8
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            const title = `🔄 Weekly GitHub Actions Update Check - ${date}`;
            
            // Check if similar issue already exists
            const { data: existingIssues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'github-actions'
            });
            
            const hasExistingIssue = existingIssues.some(issue => 
              issue.title.includes('Weekly GitHub Actions Update Check')
            );
            
            if (hasExistingIssue) {
              console.log('Similar issue already exists, skipping creation');
              return;
            }
            
            // Create issue body
            const body = `## Weekly GitHub Actions Update Check

            This is your weekly reminder to check for GitHub Actions updates.

            ### Current Actions:

            - \`actions/checkout@v5\` - [Repository](https://github.com/actions/checkout) | [Releases](https://github.com/actions/checkout/releases)
            - \`docker/setup-qemu-action@v3\` - [Repository](https://github.com/docker/setup-qemu-action) | [Releases](https://github.com/docker/setup-qemu-action/releases)
            - \`docker/setup-buildx-action@v3\` - [Repository](https://github.com/docker/setup-buildx-action) | [Releases](https://github.com/docker/setup-buildx-action/releases)
            - \`docker/login-action@v3\` - [Repository](https://github.com/docker/login-action) | [Releases](https://github.com/docker/login-action/releases)
            - \`docker/build-push-action@v6\` - [Repository](https://github.com/docker/build-push-action) | [Releases](https://github.com/docker/build-push-action/releases)
            - \`actions/github-script@v7\` - [Repository](https://github.com/actions/github-script) | [Releases](https://github.com/actions/github-script/releases)

            ### Update Process:

            1. Click the "Releases" links above to check for newer versions
            2. Review changelogs for breaking changes
            3. Update version numbers in workflow files
            4. Test the workflows after updating

            ### Automation Status:

            ✅ **Dependabot is active** - Will create PRs automatically for updates
            📅 **Weekly reminders** - This issue is created automatically

            ### Quick Actions:

            - [View all workflow files](.github/workflows/)
            - [Check Dependabot PRs](../../pulls?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot)
            - [GitHub Actions Marketplace](https://github.com/marketplace?type=actions)

            ---

            *Close this issue after reviewing the actions. A new one will be created next week.*`;
            
            // Create the issue
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['github-actions', 'maintenance', 'weekly-check']
            });
            
            console.log('Created weekly GitHub Actions update reminder issue');